# Generated by Django 4.1.4 on 2022-12-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(related_name='likes', to='main_app.post'),
        ),
    ]
